# This file was auto-generated by Fern from our API Definition.

import typing
from .user_message import UserMessage
from .system_message import SystemMessage
from .bot_message import BotMessage
from .tool_call_message import ToolCallMessage
from .tool_call_result_message import ToolCallResultMessage

ArtifactMessagesItem = typing.Union[UserMessage, SystemMessage, BotMessage, ToolCallMessage, ToolCallResultMessage]
