# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .cartesia_experimental_controls_speed import CartesiaExperimentalControlsSpeed
from .cartesia_experimental_controls_emotion import CartesiaExperimentalControlsEmotion
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class CartesiaExperimentalControls(UniversalBaseModel):
    speed: typing.Optional[CartesiaExperimentalControlsSpeed] = None
    emotion: typing.Optional[CartesiaExperimentalControlsEmotion] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
