# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ClientMessageLanguageChanged(UniversalBaseModel):
    type: typing.Literal["language-changed"] = pydantic.Field(default="language-changed")
    """
    This is the type of the message. "language-switched" is sent when the transcriber is automatically switched based on the detected language.
    """

    language: str = pydantic.Field()
    """
    This is the language the transcriber is switched to.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
