# This file was auto-generated by Fern from our API Definition.

import typing
from .client_inbound_message_add_message import ClientInboundMessageAddMessage
from .client_inbound_message_control import ClientInboundMessageControl
from .client_inbound_message_say import ClientInboundMessageSay

ClientInboundMessageMessage = typing.Union[
    ClientInboundMessageAddMessage, ClientInboundMessageControl, ClientInboundMessageSay
]
