# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CloneVoiceDto(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    This is the name of the cloned voice in the provider account.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    This is the description of your cloned voice.
    """

    labels: typing.Optional[str] = pydantic.Field(default=None)
    """
    Serialized labels dictionary for the voice.
    """

    files: typing.List[str] = pydantic.Field()
    """
    These are the files you want to use to clone your voice. Only Audio files are supported.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
