# This file was auto-generated by Fern from our API Definition.

import typing
from .trieve_knowledge_base_create import TrieveKnowledgeBaseCreate
from .trieve_knowledge_base_import import TrieveKnowledgeBaseImport

CreateTrieveKnowledgeBaseDtoCreatePlan = typing.Union[TrieveKnowledgeBaseCreate, TrieveKnowledgeBaseImport]
