# This file was auto-generated by Fern from our API Definition.

import typing
from .azure_voice import AzureVoice
from .cartesia_voice import CartesiaVoice
from .deepgram_voice import DeepgramVoice
from .eleven_labs_voice import ElevenLabsVoice
from .lmnt_voice import LmntVoice
from .neets_voice import NeetsVoice
from .open_ai_voice import OpenAiVoice
from .play_ht_voice import PlayHtVoice
from .rime_ai_voice import RimeAiVoice

CreateAssistantDtoVoice = typing.Union[
    AzureVoice,
    CartesiaVoice,
    DeepgramVoice,
    ElevenLabsVoice,
    LmntVoice,
    NeetsVoice,
    OpenAiVoice,
    PlayHtVoice,
    RimeAiVoice,
]
