# This file was auto-generated by Fern from our API Definition.

import typing

CreateAzureOpenAiCredentialDtoRegion = typing.Union[
    typing.Literal[
        "australia",
        "canada",
        "eastus2",
        "eastus",
        "france",
        "india",
        "japan",
        "northcentralus",
        "norway",
        "southcentralus",
        "sweden",
        "switzerland",
        "uk",
        "westus",
        "westus3",
    ],
    typing.Any,
]
