# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
import typing
from .say import Say
from .gather import Gather
import typing

if typing.TYPE_CHECKING:
    from .create_workflow_dto import CreateWorkflowDto
CreateWorkflowDtoNodesItem = typing.Union[Say, Gather, typing.Optional[typing.Any], "CreateWorkflowDto"]
