# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
from ..core.pydantic_utilities import UniversalBaseModel
import typing
import typing_extensions
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class CreateTwilioPhoneNumberDtoFallbackDestination_Number(UniversalBaseModel):
    """
    This is the fallback destination an inbound call will be transferred to if:

    1. `assistantId` is not set
    2. `squadId` is not set
    3. and, `assistant-request` message to the `serverUrl` fails

    If this is not set and above conditions are met, the inbound call is hung up with an error message.
    """

    type: typing.Literal["number"] = "number"
    number_e_164_check_enabled: typing_extensions.Annotated[
        typing.Optional[bool], FieldMetadata(alias="numberE164CheckEnabled")
    ] = None
    number: str
    extension: typing.Optional[str] = None
    caller_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="callerId")] = None
    message: typing.Optional[str] = None
    description: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class CreateTwilioPhoneNumberDtoFallbackDestination_Sip(UniversalBaseModel):
    """
    This is the fallback destination an inbound call will be transferred to if:

    1. `assistantId` is not set
    2. `squadId` is not set
    3. and, `assistant-request` message to the `serverUrl` fails

    If this is not set and above conditions are met, the inbound call is hung up with an error message.
    """

    type: typing.Literal["sip"] = "sip"
    sip_uri: typing_extensions.Annotated[str, FieldMetadata(alias="sipUri")]
    message: typing.Optional[str] = None
    description: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


CreateTwilioPhoneNumberDtoFallbackDestination = typing.Union[
    CreateTwilioPhoneNumberDtoFallbackDestination_Number, CreateTwilioPhoneNumberDtoFallbackDestination_Sip
]
