# This file was auto-generated by Fern from our API Definition.

import typing
from .semantic_edge_condition import SemanticEdgeCondition
from .programmatic_edge_condition import ProgrammaticEdgeCondition

EdgeCondition = typing.Union[SemanticEdgeCondition, ProgrammaticEdgeCondition]
