# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
from ..core.pydantic_utilities import UniversalBaseModel
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic
from .regex_option import RegexOption


class FormatPlanReplacementsItem_Exact(UniversalBaseModel):
    type: typing.Literal["exact"] = "exact"
    key: str
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class FormatPlanReplacementsItem_Regex(UniversalBaseModel):
    type: typing.Literal["regex"] = "regex"
    regex: str
    options: typing.Optional[typing.List[RegexOption]] = None
    value: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


FormatPlanReplacementsItem = typing.Union[FormatPlanReplacementsItem_Exact, FormatPlanReplacementsItem_Regex]
