# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import typing
from .invite_user_dto_role import InviteUserDtoRole
import typing_extensions
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class InviteUserDto(UncheckedBaseModel):
    emails: typing.List[str]
    role: InviteUserDtoRole
    redirect_to: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="redirectTo")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
