# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import typing_extensions
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class KnowledgeBase(UniversalBaseModel):
    provider: typing.Literal["canonical"] = "canonical"
    top_k: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="topK")] = None
    file_ids: typing_extensions.Annotated[typing.List[str], FieldMetadata(alias="fileIds")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
