# This file was auto-generated by Fern from our API Definition.

import typing

OpenAiVoiceId = typing.Union[
    typing.Literal["alloy", "echo", "fable", "onyx", "nova", "shimmer", "ash", "ballad", "coral", "sage", "verse"],
    typing.Any,
]
