# This file was auto-generated by Fern from our API Definition.

import typing

ServerMessageStatusUpdateStatus = typing.Union[
    typing.Literal["queued", "ringing", "in-progress", "forwarding", "ended"], typing.Any
]
