# This file was auto-generated by Fern from our API Definition.

import typing
from .model_based_condition import ModelBasedCondition
from .rule_based_condition import RuleBasedCondition

StepDestinationConditionsItem = typing.Union[ModelBasedCondition, RuleBasedCondition]
