# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import pydantic
from .structured_data_plan import StructuredDataPlan
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class StructuredDataMultiPlan(UncheckedBaseModel):
    key: str = pydantic.Field()
    """
    This is the key of the structured data plan in the catalog.
    """

    plan: StructuredDataPlan = pydantic.Field()
    """
    This is an individual structured data plan in the catalog.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
