# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .artifact import Artifact
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class TestSuiteRunTestAttemptCall(UniversalBaseModel):
    artifact: Artifact = pydantic.Field()
    """
    This is the artifact associated with the call.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
