# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .test_suite_test_voice import TestSuiteTestVoice
import pydantic
from .pagination_meta import PaginationMeta
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class TestSuiteTestsPaginatedResponse(UniversalBaseModel):
    results: typing.List[TestSuiteTestVoice] = pydantic.Field()
    """
    A list of test suite tests.
    """

    metadata: PaginationMeta = pydantic.Field()
    """
    Metadata about the pagination.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
