# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class TestSuitePhoneNumber(UncheckedBaseModel):
    provider: typing.Literal["test-suite"] = pydantic.Field(default="test-suite")
    """
    This is the provider of the phone number.
    """

    number: str = pydantic.Field()
    """
    This is the phone number that is being tested.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
