# This file was auto-generated by Fern from our API Definition.

import typing

TrieveKnowledgeBaseVectorStoreSearchPlanSearchType = typing.Union[
    typing.Literal["fulltext", "semantic", "hybrid", "bm25"], typing.Any
]
