# This file was auto-generated by Fern from our API Definition.

import typing
from .make_tool_provider_details import MakeToolProviderDetails
from .ghl_tool_provider_details import GhlToolProviderDetails
from .function_tool_provider_details import FunctionToolProviderDetails

UpdateToolTemplateDtoProviderDetails = typing.Union[
    MakeToolProviderDetails, GhlToolProviderDetails, FunctionToolProviderDetails
]
