# This file was auto-generated by Fern from our API Definition.

import typing
from .say import Say
from .gather import Gather
from .api_request import ApiRequest
from .hangup import Hangup
from .transfer import Transfer

WorkflowNodesItem = typing.Union[Say, Gather, ApiRequest, Hangup, Transfer]
