# This file was auto-generated by Fern from our API Definition.

import typing
from .say import Say
from .gather import Gather
from .create_workflow_dto import CreateWorkflowDto

WorkflowNodesItem = typing.Union[Say, Gather, typing.Optional[typing.Any], CreateWorkflowDto]
