# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.create_byo_phone_number_dto import CreateByoPhoneNumberDto
from ...types.create_twilio_phone_number_dto import CreateTwilioPhoneNumberDto
from ...types.create_vonage_phone_number_dto import CreateVonagePhoneNumberDto
from ...types.create_vapi_phone_number_dto import CreateVapiPhoneNumberDto

PhoneNumbersCreateRequest = typing.Union[
    CreateByoPhoneNumberDto, CreateTwilioPhoneNumberDto, CreateVonagePhoneNumberDto, CreateVapiPhoneNumberDto
]
