# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.anyscale_model import AnyscaleModel
from ...types.anthropic_model import AnthropicModel
from ...types.custom_llm_model import CustomLlmModel
from ...types.deep_infra_model import DeepInfraModel
from ...types.groq_model import GroqModel
from ...types.open_ai_model import OpenAiModel
from ...types.open_router_model import OpenRouterModel
from ...types.perplexity_ai_model import PerplexityAiModel
from ...types.together_ai_model import TogetherAiModel
from ...types.vapi_model import VapiModel

UpdateAssistantDtoModel = typing.Union[
    AnyscaleModel,
    AnthropicModel,
    CustomLlmModel,
    DeepInfraModel,
    GroqModel,
    OpenAiModel,
    OpenRouterModel,
    PerplexityAiModel,
    TogetherAiModel,
    VapiModel,
]
