# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.deepgram_transcriber import DeepgramTranscriber
from ...types.gladia_transcriber import GladiaTranscriber
from ...types.talkscriber_transcriber import TalkscriberTranscriber

UpdateAssistantDtoTranscriber = typing.Union[DeepgramTranscriber, GladiaTranscriber, TalkscriberTranscriber]
