# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.say import Say
from ...types.gather import Gather
from ...types.api_request import ApiRequest
from ...types.hangup import Hangup
from ...types.transfer import Transfer

UpdateWorkflowDtoNodesItem = typing.Union[Say, Gather, ApiRequest, Hangup, Transfer]
