# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.test_suite_test_voice import TestSuiteTestVoice
from ...types.test_suite_test_chat import TestSuiteTestChat

TestSuiteTestControllerCreateResponse = typing.Union[TestSuiteTestVoice, TestSuiteTestChat]
