# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations
from ...core.pydantic_utilities import UniversalBaseModel
import typing
from ...types.create_conversation_block_dto_messages_item import CreateConversationBlockDtoMessagesItem
import typing_extensions
from ...types.json_schema import JsonSchema
from ...core.serialization import FieldMetadata
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic
from ...types.create_tool_call_block_dto_messages_item import CreateToolCallBlockDtoMessagesItem
from ...types.create_tool_call_block_dto_tool import CreateToolCallBlockDtoTool
from ...types.create_workflow_block_dto_messages_item import CreateWorkflowBlockDtoMessagesItem
from ...core.pydantic_utilities import update_forward_refs


class BlocksCreateRequest_Conversation(UniversalBaseModel):
    type: typing.Literal["conversation"] = "conversation"
    messages: typing.Optional[typing.List[CreateConversationBlockDtoMessagesItem]] = None
    input_schema: typing_extensions.Annotated[typing.Optional[JsonSchema], FieldMetadata(alias="inputSchema")] = None
    output_schema: typing_extensions.Annotated[typing.Optional[JsonSchema], FieldMetadata(alias="outputSchema")] = None
    instruction: str
    name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class BlocksCreateRequest_ToolCall(UniversalBaseModel):
    type: typing.Literal["tool-call"] = "tool-call"
    messages: typing.Optional[typing.List[CreateToolCallBlockDtoMessagesItem]] = None
    input_schema: typing_extensions.Annotated[typing.Optional[JsonSchema], FieldMetadata(alias="inputSchema")] = None
    output_schema: typing_extensions.Annotated[typing.Optional[JsonSchema], FieldMetadata(alias="outputSchema")] = None
    tool: typing.Optional[CreateToolCallBlockDtoTool] = None
    tool_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="toolId")] = None
    name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class BlocksCreateRequest_Workflow(UniversalBaseModel):
    type: typing.Literal["workflow"] = "workflow"
    messages: typing.Optional[typing.List[CreateWorkflowBlockDtoMessagesItem]] = None
    input_schema: typing_extensions.Annotated[typing.Optional[JsonSchema], FieldMetadata(alias="inputSchema")] = None
    output_schema: typing_extensions.Annotated[typing.Optional[JsonSchema], FieldMetadata(alias="outputSchema")] = None
    steps: typing.Optional[typing.List["CreateWorkflowBlockDtoStepsItem"]] = None
    name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from ...types.callback_step import CallbackStep  # noqa: E402
from ...types.create_workflow_block_dto import CreateWorkflowBlockDto  # noqa: E402
from ...types.handoff_step import HandoffStep  # noqa: E402
from ...types.create_workflow_block_dto_steps_item import CreateWorkflowBlockDtoStepsItem  # noqa: E402

BlocksCreateRequest = typing.Union[
    BlocksCreateRequest_Conversation, BlocksCreateRequest_ToolCall, BlocksCreateRequest_Workflow
]
update_forward_refs(CallbackStep, BlocksCreateRequest_Workflow=BlocksCreateRequest_Workflow)
update_forward_refs(CreateWorkflowBlockDto, BlocksCreateRequest_Workflow=BlocksCreateRequest_Workflow)
update_forward_refs(HandoffStep, BlocksCreateRequest_Workflow=BlocksCreateRequest_Workflow)
update_forward_refs(BlocksCreateRequest_Workflow)
