# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.create_conversation_block_dto import CreateConversationBlockDto
from ...types.create_tool_call_block_dto import CreateToolCallBlockDto
from ...types.create_workflow_block_dto import CreateWorkflowBlockDto

BlocksCreateRequest = typing.Union[CreateConversationBlockDto, CreateToolCallBlockDto, CreateWorkflowBlockDto]
