# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.handoff_step import HandoffStep
from ...types.callback_step import CallbackStep

UpdateBlockDtoStepsItem = typing.Union[HandoffStep, CallbackStep]
